import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import React from 'react'
import { SWRProvider } from '@/app/swr-provider'
import {proximaNova} from "@/app/font";

// const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Metale',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, viewport-fit=contain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={proximaNova.className}>
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  )
}
